Repository BasisResearch/effectful, pull requests merged in 2025-08, with the labels that each got.

#324 Add support for `dataclass` in `evaluate`
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  tests/test_ops_syntax.py
Labels: status:awaiting review

#334 Absorb `call` into `CallableTerm`
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  tests/test_ops_syntax.py
Labels: status:awaiting review, refactor

#335 Remove `handlers.numbers`
  README.rst
  docs/source/effectful.rst
  docs/source/lambda_.py
  docs/source/readme_example.py
  docs/source/semi_ring.py
  effectful/handlers/jax/_handlers.py
  effectful/handlers/numbers.py
  effectful/handlers/torch.py
  effectful/ops/syntax.py
  tests/test_handlers_numbers.py
  tests/test_ops_semantics.py
  tests/test_ops_syntax.py
Labels: status:awaiting review, refactor

#344 Fix lambda_example docstring
  docs/source/lambda_example.rst
Labels: documentation, status:awaiting review

#342 Convert `syntactic_eq` to a singledispatch and add tensor support
  effectful/handlers/jax/_handlers.py
  effectful/handlers/torch.py
  effectful/ops/syntax.py
  tests/test_handlers_jax.py
  tests/test_handlers_torch.py
  tests/test_ops_syntax.py
Labels: status:awaiting review

#343 Make `defdata` and `__fvs_rule__` rely on `inspect.BoundArguments`
  effectful/handlers/jax/_terms.py
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  effectful/ops/types.py
  tests/test_ops_syntax.py
Labels: bug, status:awaiting review
