Repository BasisResearch/effectful, pull requests merged in 2025-01, with the labels that each got.

#103 Copy docs publishing workflow from chirho
  .github/workflows/publish_docs.yml
Labels: documentation, blocked

#182 Add missing file with generated docs
  docs/source/effectful.rst
Labels: documentation

#185 Move docs requirements.txt to correct location
  docs/source/requirements.txt
Labels: bug, documentation, status:awaiting review

#186 Change NoDefaultRule to NotImplementedError
  docs/source/lambda_.py
  docs/source/semi_ring.py
  effectful/handlers/numbers.py
  effectful/handlers/torch.py
  effectful/internals/base_impl.py
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  tests/test_handlers_numbers.py
  tests/test_ops_semantics.py
  tests/test_ops_syntax.py
Labels: status:awaiting review, refactor, blocked

#178 Avoid pushing Terms through arbitrary Python code
  docs/source/lambda_.py
  docs/source/semi_ring.py
  effectful/handlers/numbers.py
  effectful/handlers/torch.py
  effectful/internals/base_impl.py
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  tests/test_handlers_numbers.py
  tests/test_ops_semantics.py
  tests/test_ops_syntax.py
Labels: bug, status:awaiting review, usability

#191 Fix introduction.ipynb failures
  docs/source/introduction.ipynb
Labels: bug, status:awaiting review, example

#187 Fix some issues with docs
  docs/source/effectful.rst
  docs/source/introduction.ipynb
  docs/source/requirements.txt
  effectful/handlers/numbers.py
Labels: bug, status:awaiting review

#194 Another try at getting the docs requirements right
  docs/source/requirements.txt
Labels: status:awaiting review

#196 Fix failing minipyro test
  docs/source/minipyro.py
  tests/conftest.py
Labels: bug, status:awaiting review, example, testing

#198 Fix readme example
  README.rst
Labels: status:awaiting review

#200 Weaken the typing of `Interpretation`s to prevent type errors in common use
  effectful/ops/semantics.py
  tests/test_ops_semantics.py
Labels: bug, status:awaiting review

#199 Give fresh names to Operations created from types or Operations
  effectful/internals/base_impl.py
  effectful/ops/syntax.py
  tests/test_ops_syntax.py
Labels: bug, status:awaiting response, usability

#201 Compute sizesof(Distribution) without sampling
  effectful/handlers/indexed.py
  effectful/handlers/pyro.py
  effectful/handlers/torch.py
Labels: enhancement, status:awaiting review

#180 Move `_BaseOperation.__free_rule__` into specification
  docs/source/introduction.ipynb
  effectful/handlers/numbers.py
  effectful/handlers/torch.py
  effectful/internals/base_impl.py
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  effectful/ops/types.py
  tests/test_handlers_numbers.py
Labels: status:awaiting response, refactor

#209 Move internals.base_impl into ops.syntax
  effectful/internals/base_impl.py
  effectful/ops/syntax.py
  effectful/ops/types.py
Labels: status:awaiting review, refactor

#211 Fix `BaseOperation.__repr_rule__`
  effectful/ops/syntax.py
  tests/test_ops_syntax.py
Labels: bug

#210 Bump version to 0.1.0
  setup.py
Labels: blocked

#212 Fix missing typing of to_tensor
  effectful/handlers/torch.py
Labels: enhancement, status:awaiting review

#217 Enable doctests in ci
  effectful/handlers/indexed.py
  effectful/handlers/torch.py
  effectful/ops/syntax.py
  scripts/test.sh
Labels: status:awaiting review

#223 Fix bugs in PyroShim
  effectful/handlers/pyro.py
Labels: status:awaiting review

#219 Drop isort, black, flake8 in favor of ruff
  effectful/handlers/indexed.py
  effectful/handlers/pyro.py
  effectful/handlers/torch.py
  effectful/internals/runtime.py
  effectful/ops/semantics.py
  effectful/ops/syntax.py
  effectful/ops/types.py
  scripts/clean.sh
  scripts/lint.sh
  setup.py
  tests/test_examples_minipyro.py
  tests/test_handlers_numbers.py
  tests/test_handlers_pyro.py
  tests/test_handlers_torch.py
  tests/test_ops_semantics.py
  tests/test_ops_syntax.py
Labels: status:awaiting review
